### ISSUE TITLE
How to call a Detail Activity

### ISSUE THREAD

**Issue by blfernandez** [kasim1011/OdooJsonRpcClient#2]
How to Call a CustumerDetail, for update and delete?

override fun onBindViewHolder(baseHolder: RecyclerView.ViewHolder, basePosition: Int) {
        super.onBindViewHolder(baseHolder, basePosition)
        val position = baseHolder.adapterPosition
        when (getItemViewType(basePosition)) {
            VIEW_TYPE_ITEM -> {
                val holder = baseHolder as CustomerViewHolder
                val item = items[position] as Customer
                val binding = holder.binding
                binding.customer = item
                if (!binding.root.hasOnClickListeners()) {
                    binding.root.setOnClickListener {
                        // val clickedPosition = holder.adapterPosition
                        // val clickedItem = items[clickedPosition] as Customer
                    }
                }
            }
        }
}

**Comment by kasim1011** [comment]
Hello @blfernandez 

There is no Customer Detail Activity in Sample app.

You can surely add one, by passing the `customer object (POJO)` to new **CutsomerDetailActivity / CustomerDetailFragment** and display customer details

If you want additional data to display you can use [`searchRead`](https://github.com/kasim1011/OdooJsonRpcClient#searchread) for that.

**Comment by blfernandez** [comment]
Ready
