### ISSUE TITLE
How to implement a JsonElement on layout

### ISSUE THREAD

**Issue by blfernandez** [kasim1011/OdooJsonRpcClient#3]
on Entities:

    @Expose
    @SerializedName("afiliado_id")
    val afiliadoid: JsonElement,

How to impement on Layout

    android:text="@{UtilsKt.trimFalse(prestamos.afiliadoid)}"

Error:

    msg:cannot find method trimFalse(com.google.gson.JsonElement) in class io.gripxtech.odoojsonrpcclient.UtilsKt

**Comment by kasim1011** [comment]
Did you import `UtilsKt` in xml layout file?

https://github.com/kasim1011/OdooJsonRpcClient/blob/d60317f0939adfd2573dead3053cade049aefee7/app/src/main/res/layout/item_view_customer.xml#L8

Use `JsonElement` for `Many2One` field. In layout XML, reference `JsonElement` using **asManyToOne** function from `UtilsKt`

https://github.com/kasim1011/OdooJsonRpcClient/blob/d60317f0939adfd2573dead3053cade049aefee7/app/src/main/java/io/gripxtech/odoojsonrpcclient/Utils.kt#L154

`android:text="@{UtilsKt.getAsManyToOne(prestamos.afiliadoid).name}"`

**Comment by Aliasgar0512** [comment]
Nice use of two way data binding though!!.
