### ISSUE TITLE
Handshake failed

### ISSUE THREAD

**Issue by fanha99** [kasim1011/OdooJsonRpcClient#4]
hi
I tested on my xiaomi Mi 6 which is installed the chinese version of rom.
when I try to connect to testing server (odoo 11) on Lan. I got error on the app: "Handshake failed".

the debug info of app:
```
D/OkHttp: --> POST https://192.168.5.120:8079/web/webclient/version_info
    Content-Type: application/json; charset=UTF-8
    Content-Length: 54
    User-Agent: MI 6
D/OkHttp: {"id":"1","jsonrpc":"2.0","method":"call","params":{}}
    --> END POST (54-byte body)
D/OkHttp: <-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: Handshake failed

```
on the odoo server I got this message:

```
code 400, message Bad request version ('\x00\x02\x01\x00\x00')
           hhttp/1.1    " HTTPStatus.BAD_REQUEST
```

what can I do?

![error](https://user-images.githubusercontent.com/1172848/52869078-71b3f880-3177-11e9-900e-6d7908646eee.png)

**Comment by fanha99** [comment]
sorry, after update the code and rebuild. I can input the username and password now.
but there is no database to choice, so still couldn't login.

**Comment by fanha99** [comment]
update: 
after remove "dbfilter = ^%d$" in the odoo config file, I can connect to my LAN server now.

**Comment by kasim1011** [comment]
@fanha99 

Thanks for sharing the above information. It may helpful to other users.
