### ISSUE TITLE
how to search "phone" ilike "A" OR "mobile" ilike "A"?

### ISSUE THREAD

**Issue by fanha99** [kasim1011/OdooJsonRpcClient#5]
hi,
I want to search a partner:
"phone" ilike "A" **OR** "mobile" ilike "A"?

**Comment by kasim1011** [comment]
@fanha99 

You can use [`SearchRead`](https://github.com/kasim1011/OdooJsonRpcClient#searchread) on `res.partner` for searching for partner records based on `phone` and / or `mobile` or other fields.

for operators you can refer [Available domain operators in Openerp / Odoo?](https://stackoverflow.com/a/29443027/3702021)

for **"phone" ilike "A" **OR** "mobile" ilike "A"?**. you can use `phone`, `mobile` or other fields. it depends on which field is getting used on your system for storing partner's contact number.

**Comment by fanha99** [comment]
for exam:
```
Odoo.searchRead(model = "res.partner", fields = listOf(
        "id", "name", "email", "company_name"
), domain = listOf(listOf("phone", "ilike", callnumber)), offset = 0, limit = 4, sort = "name ASC") {
```
with this exam I can search partner with the field "phone" is the same to callnumber

I want to check: field "phone" is the same to callnumber OR field "mobile" is the same to callnumber

**Comment by fanha99** [comment]
`listOf("|" , listOf("phone", "ilike", number), listOf("mobile", "ilike", number))`
done, many thx
