### ISSUE TITLE
"companyName" is not showup

### ISSUE THREAD

**Issue by fanha99** [kasim1011/OdooJsonRpcClient#6]
in "item_view_customer.xml"
there is a "companyName" which is never show up.
I'm using odoo 11.

**Comment by kasim1011** [comment]
@fanha99 

Please put the Network Request & Response Log.

**Comment by fanha99** [comment]
as the result of **SearchRead** in your readme: field "**company_name**" is always **false**
```
{
  "result": {
    "length": 25,
    "records": [
      {
        "id": 9,
        "name": "Agrolait",
        "email": "agrolait@yourcompany.example.com",
        "company_name": false
      },
      {
        "id": 31,
        "name": "Ayaan Agarwal",
        "email": "ayaan.agarwal@bestdesigners.example.com",
        "company_name": false
      },
      {
        "id": 37,
        "name": "Benjamin Flores",
        "email": "benjamin.flores@nebula.example.com",
        "company_name": false
      },
      {
        "id": 13,
        "name": "Camptocamp",
        "email": "camptocamp@yourcompany.example.com",
        "company_name": false
      }
    ]
  }
}
```

**Comment by fanha99** [comment]
_company_name_ of partner: **Benjamin Flores** must be **Camptocamp**

**Comment by fanha99** [comment]
@kasim1011 
I'm wonder what is the role of the field **companyName** in the **item_view_customer.xml**?
is that to show the parent company of partner?
If yes, may I make a pull request for it?

**Comment by kasim1011** [comment]
@fanha99 Yes Sure, It is for to show the parent company of partner. Go ahead and make one PR
